#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-rjstat
Version  : 0.4.2
Release  : 38
URL      : https://cran.r-project.org/src/contrib/rjstat_0.4.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rjstat_0.4.2.tar.gz
Summary  : Handle 'JSON-stat' Format in R
Group    : Development/Tools
License  : MIT
Requires: R-checkmate
Requires: R-jsonlite
BuildRequires : R-checkmate
BuildRequires : R-jsonlite
BuildRequires : buildreq-R

%description
Not all features are supported, especially the extensive metadata
    features of 'JSON-stat'.

%prep
%setup -q -c -n rjstat
cd %{_builddir}/rjstat

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647620377

%install
export SOURCE_DATE_EPOCH=1647620377
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rjstat
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rjstat
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rjstat
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc rjstat || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rjstat/DESCRIPTION
/usr/lib64/R/library/rjstat/INDEX
/usr/lib64/R/library/rjstat/LICENSE
/usr/lib64/R/library/rjstat/Meta/Rd.rds
/usr/lib64/R/library/rjstat/Meta/features.rds
/usr/lib64/R/library/rjstat/Meta/hsearch.rds
/usr/lib64/R/library/rjstat/Meta/links.rds
/usr/lib64/R/library/rjstat/Meta/nsInfo.rds
/usr/lib64/R/library/rjstat/Meta/package.rds
/usr/lib64/R/library/rjstat/NAMESPACE
/usr/lib64/R/library/rjstat/R/rjstat
/usr/lib64/R/library/rjstat/R/rjstat.rdb
/usr/lib64/R/library/rjstat/R/rjstat.rdx
/usr/lib64/R/library/rjstat/extdata/oecd.json
/usr/lib64/R/library/rjstat/help/AnIndex
/usr/lib64/R/library/rjstat/help/aliases.rds
/usr/lib64/R/library/rjstat/help/paths.rds
/usr/lib64/R/library/rjstat/help/rjstat.rdb
/usr/lib64/R/library/rjstat/help/rjstat.rdx
/usr/lib64/R/library/rjstat/html/00Index.html
/usr/lib64/R/library/rjstat/html/R.css
/usr/lib64/R/library/rjstat/tests/testthat.R
/usr/lib64/R/library/rjstat/tests/testthat/bundle.json
/usr/lib64/R/library/rjstat/tests/testthat/canada.json
/usr/lib64/R/library/rjstat/tests/testthat/collection.json
/usr/lib64/R/library/rjstat/tests/testthat/collection_sample.json
/usr/lib64/R/library/rjstat/tests/testthat/dataset.json
/usr/lib64/R/library/rjstat/tests/testthat/dataset2.json
/usr/lib64/R/library/rjstat/tests/testthat/galicia.json
/usr/lib64/R/library/rjstat/tests/testthat/hierarchy.json
/usr/lib64/R/library/rjstat/tests/testthat/nonexistent.json
/usr/lib64/R/library/rjstat/tests/testthat/notjsonstat.json
/usr/lib64/R/library/rjstat/tests/testthat/oecd-canada-col.json
/usr/lib64/R/library/rjstat/tests/testthat/oecd.json
/usr/lib64/R/library/rjstat/tests/testthat/oecd_tidy.json
/usr/lib64/R/library/rjstat/tests/testthat/order.json
/usr/lib64/R/library/rjstat/tests/testthat/test-classes.R
/usr/lib64/R/library/rjstat/tests/testthat/test-columns.R
/usr/lib64/R/library/rjstat/tests/testthat/test-constructor.R
/usr/lib64/R/library/rjstat/tests/testthat/test-datasets.R
/usr/lib64/R/library/rjstat/tests/testthat/test-factors.R
/usr/lib64/R/library/rjstat/tests/testthat/test-input.R
/usr/lib64/R/library/rjstat/tests/testthat/test-jsonstat_accessors.R
/usr/lib64/R/library/rjstat/tests/testthat/test-jsonstat_methods.R
/usr/lib64/R/library/rjstat/tests/testthat/test-output.R
/usr/lib64/R/library/rjstat/tests/testthat/test-values.R
/usr/lib64/R/library/rjstat/tests/testthat/test-warnings.R
/usr/lib64/R/library/rjstat/tests/testthat/us-gsp.json
/usr/lib64/R/library/rjstat/tests/testthat/us-labor.json
/usr/lib64/R/library/rjstat/tests/testthat/us-unr.json
